# TODO: Update regularly
# TODO: Must create filebrowser.db, how to avoid?

# Note: I don't think podman-compose supports the `develop` or `config`
# features. It also silently ignores unknown fields AFAICT.

services:

  # docs say:
  # docker run \
      # -v /path/to/root:/srv \
      # -v /path/filebrowser.db:/database.db \
      # -v /path/.filebrowser.json:/.filebrowser.json \
      # -u $(id -u):$(id -g) \
      # -p 8080:80 \
      #
  file-browser:
    image: docker.io/filebrowser/filebrowser
    volumes:
      - "data:/srv"
      - type: bind
        source: ./system-data/filebrowser.db
        target: /database.db
        external: true
    networks:
      - nas

  # docs say:
  # docker run -d -p 8080:8080 -p 80:80 \
  #  -v $PWD/traefik.yml:/etc/traefik/traefik.yml traefik:v3.3
  caddy:
    image: docker.io/caddy:2
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nas
    command: caddy run --config=/Caddyfile
    volumes:
      - ./Caddyfile:/Caddyfile

  # docs say:
  # podman run \
  #   -p 9000:9000 \
  #   -p 9001:9001 \
  #   -v ~/minio/data:/data \
  #   -e "MINIO_ROOT_USER=ROOTNAME" \
  #   -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
  #   quay.io/minio/minio server /data --console-address ":9001"
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: minio server /data --console-address ":9001"
    # This should contain MINIO_ROOT_USSER and MINIO_ROOT_PASSWORD
    env_file: ./secrets/minio.env
    volumes:
      - "data:/data"
    networks:
     - nas

The example above works this way:

volumes:
  # The actual NAS filesystem. Will probably be ZFS.
  data:

networks:
  nas:
    name: nas