- hosts: all
  vars:
    nas_base_dir: "{{ ansible_user_dir }}/nas"
    # This is where we'll store stuff on the NAS host that needs to persiste
    # across container restarts.
    nas_system_data_dir: "{{ nas_base_dir }}/system-data"
    # This is coupled with compose.yaml.
    filebrowser_database: "{{ nas_system_data_dir }}/filebrowser.db"
  tasks:

    # I dunno why installing the Ansible requirements is not just a default part
    # of the process of running a playbook, but for whatever reason it isn't.
    # I guess maybe they fucked up the dependency management somehow.
    # Anyway, whatever, just install it in the playbook. This is definitely not
    # Best Practice.
    - name: Install Ansible dependencies
      local_action: command ansible-galaxy install artis3n.tailscale
      tags: ansible

    - name: Install NAS dependencies
      package:
        name:
          - zfsutils-linux
        state: present
      tags: base

    - name: Ensure NAS state directories exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nas_base_dir }}"
        - "{{ nas_system_data_dir }}"
      tags: base

    - name: Set up unprivileged HTTP server access
      sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: 80
      become: true  # sudo
      tags: base

    - name: Include Tailscale role if auth key is set
      include_role:
        name: artis3n.tailscale
      when: tailscale_authkey is defined
      tags: tailscale

    # Work around dumb docker-compose behaviour where it behaves differently
    # depending on whether a file exists on the host.
    # We need to create the
    - name: Ensure FileBrowser database exists
      copy:
        content: ""
        dest: "{{ filebrowser_database }}"
        force: false  # Don't create if exists
      tags: filebrowser

    # Adapted from https://github.com/geerlingguy/arm-nas/blob/master/main.yml
    - name: Create ZFS pools.
      # zfs_pools will be read from host_vars. Each entry will be set as the
      # `item` in the command above.
      loop: "{{ zfs_pools }}"
      ansible.builtin.command:
        # Note - the 'members' contains the raidz1 bit.
        cmd: "zpool create -m {{ item.mount_point }} {{ item.name }} {{ item.members }} -f"
        # Avoid trying to repeat the command above. There might be a tidier way
        # to do it than checking if the mountpoint exists, but whatever.
        creates: "{{ item.mount_point }}"
      become: true  # sudo
      tags: zfs

    - name: Create Docker system group
      group:
        name: docker
        state: present
        system: yes
      become: true
      tags: docker

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: true
      tags: docker

    - name: Install Docker snap
      snap:
        name:
          docker
      become: true
      tags: docker